version: "3.9"
services:
    db:
        image: postgres:alpine
        container_name: django-db
        env_file:
            ./.env
        volumes:
            - ./data/postgres/data:/var/lib/postgresql/data

    web:
        container_name: django-web
        build: ./src
        env_file:
            ./.env
        volumes:
            - ./src:/app
        command: pipenv run start
        ports:
            - '8000:8000'
        depends_on:
            - db

volumes:
    pgdata:
    venvs: