# Generated by Django 3.2 on 2021-04-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
